# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vllm_criu_engine_pb2 as vllm__criu__engine__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vllm_criu_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VLLMEngineServiceStub(object):
    """Main VLLMEngine service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Initialize',
                request_serializer=vllm__criu__engine__pb2.InitializeRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Start',
                request_serializer=vllm__criu__engine__pb2.StartRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.StartResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/CheckHealth',
                request_serializer=vllm__criu__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/vllm_engine.VLLMEngineService/Chat',
                request_serializer=vllm__criu__engine__pb2.ChatRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.Completions = channel.unary_stream(
                '/vllm_engine.VLLMEngineService/Completions',
                request_serializer=vllm__criu__engine__pb2.CompletionsRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.CompletionsResponse.FromString,
                _registered_method=True)
        self.Embeddings = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Embeddings',
                request_serializer=vllm__criu__engine__pb2.EmbeddingsRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.EmbeddingsResponse.FromString,
                _registered_method=True)
        self.Transcriptions = channel.unary_stream(
                '/vllm_engine.VLLMEngineService/Transcriptions',
                request_serializer=vllm__criu__engine__pb2.TranscriptionsRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.TranscriptionsResponse.FromString,
                _registered_method=True)
        self.Score = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Score',
                request_serializer=vllm__criu__engine__pb2.ScoreRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.Tokenize = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Tokenize',
                request_serializer=vllm__criu__engine__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.Detokenize = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Detokenize',
                request_serializer=vllm__criu__engine__pb2.DetokenizeRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.DetokenizeResponse.FromString,
                _registered_method=True)
        self.ResetPrefixCache = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/ResetPrefixCache',
                request_serializer=vllm__criu__engine__pb2.ResetPrefixCacheRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.ResetPrefixCacheResponse.FromString,
                _registered_method=True)
        self.Sleep = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Sleep',
                request_serializer=vllm__criu__engine__pb2.SleepRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.SleepResponse.FromString,
                _registered_method=True)
        self.Wakeup = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Wakeup',
                request_serializer=vllm__criu__engine__pb2.WakeupRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.WakeupResponse.FromString,
                _registered_method=True)
        self.IsSleeping = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/IsSleeping',
                request_serializer=vllm__criu__engine__pb2.IsSleepingRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.IsSleepingResponse.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Pause',
                request_serializer=vllm__criu__engine__pb2.PauseRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.PauseResponse.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/Resume',
                request_serializer=vllm__criu__engine__pb2.ResumeRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.ResumeResponse.FromString,
                _registered_method=True)
        self.IsPaused = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/IsPaused',
                request_serializer=vllm__criu__engine__pb2.IsPausedRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.IsPausedResponse.FromString,
                _registered_method=True)
        self.StartProfile = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/StartProfile',
                request_serializer=vllm__criu__engine__pb2.StartProfileRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.StartProfileResponse.FromString,
                _registered_method=True)
        self.StopProfile = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/StopProfile',
                request_serializer=vllm__criu__engine__pb2.StopProfileRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.StopProfileResponse.FromString,
                _registered_method=True)
        self.ResolveLora = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/ResolveLora',
                request_serializer=vllm__criu__engine__pb2.ResolveLoraRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.ResolveLoraResponse.FromString,
                _registered_method=True)
        self.CollectiveRpc = channel.unary_unary(
                '/vllm_engine.VLLMEngineService/CollectiveRpc',
                request_serializer=vllm__criu__engine__pb2.CollectiveRpcRequest.SerializeToString,
                response_deserializer=vllm__criu__engine__pb2.CollectiveRpcResponse.FromString,
                _registered_method=True)


class VLLMEngineServiceServicer(object):
    """Main VLLMEngine service
    """

    def Initialize(self, request, context):
        """Lifecycle methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Generation methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Completions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcriptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Score(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tokenize(self, request, context):
        """Tokenization methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detokenize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPrefixCache(self, request, context):
        """Cache management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sleep(self, request, context):
        """Power management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Wakeup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsSleeping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsPaused(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartProfile(self, request, context):
        """Profiling
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveLora(self, request, context):
        """LoRA management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectiveRpc(self, request, context):
        """Collective RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VLLMEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=vllm__criu__engine__pb2.InitializeRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.InitializeResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=vllm__criu__engine__pb2.StartRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.StartResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=vllm__criu__engine__pb2.HealthRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.HealthResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=vllm__criu__engine__pb2.ChatRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.ChatResponse.SerializeToString,
            ),
            'Completions': grpc.unary_stream_rpc_method_handler(
                    servicer.Completions,
                    request_deserializer=vllm__criu__engine__pb2.CompletionsRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.CompletionsResponse.SerializeToString,
            ),
            'Embeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.Embeddings,
                    request_deserializer=vllm__criu__engine__pb2.EmbeddingsRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.EmbeddingsResponse.SerializeToString,
            ),
            'Transcriptions': grpc.unary_stream_rpc_method_handler(
                    servicer.Transcriptions,
                    request_deserializer=vllm__criu__engine__pb2.TranscriptionsRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.TranscriptionsResponse.SerializeToString,
            ),
            'Score': grpc.unary_unary_rpc_method_handler(
                    servicer.Score,
                    request_deserializer=vllm__criu__engine__pb2.ScoreRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.ScoreResponse.SerializeToString,
            ),
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=vllm__criu__engine__pb2.TokenizeRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.TokenizeResponse.SerializeToString,
            ),
            'Detokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Detokenize,
                    request_deserializer=vllm__criu__engine__pb2.DetokenizeRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.DetokenizeResponse.SerializeToString,
            ),
            'ResetPrefixCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPrefixCache,
                    request_deserializer=vllm__criu__engine__pb2.ResetPrefixCacheRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.ResetPrefixCacheResponse.SerializeToString,
            ),
            'Sleep': grpc.unary_unary_rpc_method_handler(
                    servicer.Sleep,
                    request_deserializer=vllm__criu__engine__pb2.SleepRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.SleepResponse.SerializeToString,
            ),
            'Wakeup': grpc.unary_unary_rpc_method_handler(
                    servicer.Wakeup,
                    request_deserializer=vllm__criu__engine__pb2.WakeupRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.WakeupResponse.SerializeToString,
            ),
            'IsSleeping': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSleeping,
                    request_deserializer=vllm__criu__engine__pb2.IsSleepingRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.IsSleepingResponse.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=vllm__criu__engine__pb2.PauseRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.PauseResponse.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=vllm__criu__engine__pb2.ResumeRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.ResumeResponse.SerializeToString,
            ),
            'IsPaused': grpc.unary_unary_rpc_method_handler(
                    servicer.IsPaused,
                    request_deserializer=vllm__criu__engine__pb2.IsPausedRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.IsPausedResponse.SerializeToString,
            ),
            'StartProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProfile,
                    request_deserializer=vllm__criu__engine__pb2.StartProfileRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.StartProfileResponse.SerializeToString,
            ),
            'StopProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.StopProfile,
                    request_deserializer=vllm__criu__engine__pb2.StopProfileRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.StopProfileResponse.SerializeToString,
            ),
            'ResolveLora': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveLora,
                    request_deserializer=vllm__criu__engine__pb2.ResolveLoraRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.ResolveLoraResponse.SerializeToString,
            ),
            'CollectiveRpc': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectiveRpc,
                    request_deserializer=vllm__criu__engine__pb2.CollectiveRpcRequest.FromString,
                    response_serializer=vllm__criu__engine__pb2.CollectiveRpcResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vllm_engine.VLLMEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vllm_engine.VLLMEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VLLMEngineService(object):
    """Main VLLMEngine service
    """

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Initialize',
            vllm__criu__engine__pb2.InitializeRequest.SerializeToString,
            vllm__criu__engine__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Start',
            vllm__criu__engine__pb2.StartRequest.SerializeToString,
            vllm__criu__engine__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/CheckHealth',
            vllm__criu__engine__pb2.HealthRequest.SerializeToString,
            vllm__criu__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Chat',
            vllm__criu__engine__pb2.ChatRequest.SerializeToString,
            vllm__criu__engine__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Completions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Completions',
            vllm__criu__engine__pb2.CompletionsRequest.SerializeToString,
            vllm__criu__engine__pb2.CompletionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Embeddings',
            vllm__criu__engine__pb2.EmbeddingsRequest.SerializeToString,
            vllm__criu__engine__pb2.EmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcriptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Transcriptions',
            vllm__criu__engine__pb2.TranscriptionsRequest.SerializeToString,
            vllm__criu__engine__pb2.TranscriptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Score(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Score',
            vllm__criu__engine__pb2.ScoreRequest.SerializeToString,
            vllm__criu__engine__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Tokenize',
            vllm__criu__engine__pb2.TokenizeRequest.SerializeToString,
            vllm__criu__engine__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Detokenize',
            vllm__criu__engine__pb2.DetokenizeRequest.SerializeToString,
            vllm__criu__engine__pb2.DetokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPrefixCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/ResetPrefixCache',
            vllm__criu__engine__pb2.ResetPrefixCacheRequest.SerializeToString,
            vllm__criu__engine__pb2.ResetPrefixCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sleep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Sleep',
            vllm__criu__engine__pb2.SleepRequest.SerializeToString,
            vllm__criu__engine__pb2.SleepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Wakeup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Wakeup',
            vllm__criu__engine__pb2.WakeupRequest.SerializeToString,
            vllm__criu__engine__pb2.WakeupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsSleeping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/IsSleeping',
            vllm__criu__engine__pb2.IsSleepingRequest.SerializeToString,
            vllm__criu__engine__pb2.IsSleepingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Pause',
            vllm__criu__engine__pb2.PauseRequest.SerializeToString,
            vllm__criu__engine__pb2.PauseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/Resume',
            vllm__criu__engine__pb2.ResumeRequest.SerializeToString,
            vllm__criu__engine__pb2.ResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsPaused(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/IsPaused',
            vllm__criu__engine__pb2.IsPausedRequest.SerializeToString,
            vllm__criu__engine__pb2.IsPausedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/StartProfile',
            vllm__criu__engine__pb2.StartProfileRequest.SerializeToString,
            vllm__criu__engine__pb2.StartProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/StopProfile',
            vllm__criu__engine__pb2.StopProfileRequest.SerializeToString,
            vllm__criu__engine__pb2.StopProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveLora(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/ResolveLora',
            vllm__criu__engine__pb2.ResolveLoraRequest.SerializeToString,
            vllm__criu__engine__pb2.ResolveLoraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectiveRpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vllm_engine.VLLMEngineService/CollectiveRpc',
            vllm__criu__engine__pb2.CollectiveRpcRequest.SerializeToString,
            vllm__criu__engine__pb2.CollectiveRpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
